name: psyCraftCore
version: ${project.version}
main: de.psyCraft.Core.PsyCraftCore
api-version: 1.16
authors: [ psyGamer ]
description: API for all psyCraft Game Modes

depend:
  - Multiverse-Core

commands:
  npc:
  remove:
  head:
  open:
  start: