name: psyCraftCore
version: ${project.version}
main: de.psyCraft.psyCraftCore
api-version: 1.16
authors: [ psyGamer ]
description: API for all psyCraft Game Modes

commands:
  npc:
  remove:
  head:
  open: